project:
  type: website
  output-dir: docs

website:
  title: "Personal Website"
  favicon: imgs/sit_logo.png
  navbar:
    logo: imgs/sit_logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - recipe.qmd
      - reflection.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



